=== alepostai/alepostai.github.io/contact.dtd
<!ELEMENT contact (branches, contact-info)>
<!ELEMENT branches (branch+)>
<!ELEMENT branch (name, address, phone, hours, map)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT hours (#PCDATA)>
<!ELEMENT map (#PCDATA)>
<!ELEMENT contact-info (email, phone)>
<!ELEMENT email (#PCDATA)>

=== alepostai/alepostai.github.io/contact.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE contact SYSTEM "contact.dtd">
<contact>
    <branches>
        <branch>
            <name>Surry Hills</name>
            <address>76 Devonshire St, Surry Hills NSW</address>
            <phone>02 9211 1234</phone>
            <hours>Mon - Fri: 6:00 to 14:30, Sat-Sun: 7:00 to 15:00</hours>
            <map>https://goo.gl/maps/XYZ</map>
        </branch>
        <branch>
            <name>Haymarket</name>
            <address>451 Pitt St, Haymarket Sydney, NSW</address>
            <phone>02 9262 5678</phone>
            <hours>Mon - Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</hours>
            <map>https://goo.gl/maps/XYZ</map>
        </branch>
        <branch>
            <name>Circular Quay</name>
            <address>31 Alfred Street, Circular Quay, NSW</address>
            <phone>02 8971 9101</phone>
            <hours>Mon - Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</hours>
            <map>https://goo.gl/maps/XYZ</map>
        </branch>
    </branches>
    <contact-info>
        <email>info@bryanscafe.com</email>
        <phone>General Enquiries: 02 9123 4567</phone>
    </contact-info>
</contact>
